import { DarkTheme, DefaultTheme, type Theme } from '@react-navigation/native';

export const THEME = {
  light: {
    background: '#fff9f5',
    foreground: '#3d3436',
    card: '#ffffff',
    cardForeground: '#3d3436',
    popover: '#ffffff',
    popoverForeground: '#3d3436',
    primary: '#ff7e5f',
    primaryForeground: '#ffffff',
    secondary: '#ffedea',
    secondaryForeground: '#b35340',
    muted: '#fff0eb',
    mutedForeground: '#78716c',
    accent: '#feb47b',
    accentForeground: '#3d3436',
    destructive: '#e63946',
    destructiveForeground: '#ffffff',
    border: '#ffe0d6',
    input: '#ffe0d6',
    ring: '#ff7e5f',
    radius: '0.625rem',
    chart1: '#ff7e5f',
    chart2: '#feb47b',
    chart3: '#ffcaa7',
    chart4: '#ffad8f',
    chart5: '#ce6a57',
    sidebar: '#fff0eb',
    sidebarForeground: '#3d3436',
    sidebarPrimary: '#ff7e5f',
    sidebarPrimaryForeground: '#ffffff',
    sidebarAccent: '#feb47b',
    sidebarAccentForeground: '#3d3436',
    sidebarBorder: '#ffe0d6',
    sidebarRing: '#ff7e5f',
    fontSans: 'Montserrat, sans-serif',
    fontSerif: 'Merriweather, serif',
    fontMono: 'Ubuntu Mono, monospace',
  },
  dark: {
    background: '#2a2024',
    foreground: '#f2e9e4',
    card: '#392f35',
    cardForeground: '#f2e9e4',
    popover: '#392f35',
    popoverForeground: '#f2e9e4',
    primary: '#ff7e5f',
    primaryForeground: '#ffffff',
    secondary: '#463a41',
    secondaryForeground: '#f2e9e4',
    muted: '#30272c',
    mutedForeground: '#d7c6bc',
    accent: '#feb47b',
    accentForeground: '#2a2024',
    destructive: '#e63946',
    destructiveForeground: '#ffffff',
    border: '#463a41',
    input: '#463a41',
    ring: '#ff7e5f',
    radius: '0.625rem',
    chart1: '#ff7e5f',
    chart2: '#feb47b',
    chart3: '#ffcaa7',
    chart4: '#ffad8f',
    chart5: '#ce6a57',
    sidebar: '#2a2024',
    sidebarForeground: '#f2e9e4',
    sidebarPrimary: '#ff7e5f',
    sidebarPrimaryForeground: '#ffffff',
    sidebarAccent: '#feb47b',
    sidebarAccentForeground: '#2a2024',
    sidebarBorder: '#463a41',
    sidebarRing: '#ff7e5f',
    fontSans: 'Montserrat, sans-serif',
    fontSerif: 'Merriweather, serif',
    fontMono: 'Ubuntu Mono, monospace',
  },
};

export const NAV_THEME: Record<'light' | 'dark', Theme> = {
  light: {
    ...DefaultTheme,
    colors: {
      background: THEME.light.background,
      border: THEME.light.border,
      card: THEME.light.card,
      notification: THEME.light.destructive,
      primary: THEME.light.primary,
      text: THEME.light.foreground,
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      background: THEME.dark.background,
      border: THEME.dark.border,
      card: THEME.dark.card,
      notification: THEME.dark.destructive,
      primary: THEME.dark.primary,
      text: THEME.dark.foreground,
    },
  },
};
